services:
    # Solver environment (for my own personal development/testing)
    ctf:
      build:
        context: ./participant-download
        dockerfile: participant-download/Dockerfile
      container_name: sgtechctf-solver
      stdin_open: true
      tty: true
      volumes:
        - ./challenge:/ctf/challenge
      working_dir: /ctf
      cap_add:
        - SYS_PTRACE
      security_opt:
        - seccomp:unconfined

    # Challenge server (simulates the remote CTFd deployment locally)
    server:
      build: 
        context: .
        dockerfile: Dockerfile.server
      container_name: sgtechctf-server
      ports:
        - "1337:1337"
      restart: unless-stopped